Empty Support and toroidal_propeller();
RaulBejarano/Ultimate-Toroidal-Propeller-Generator pull request #20
Opened 2023-07-23 16:16 UTC by Little-Night-Wolf

Added the empty support for the hub and fixed the missing "toroidal_propeller();" and More information in comments

2023-07-24 08:52 UTC, fj-ar approved these changes

2023-07-27 08:41 UTC, RaulBejarano requested changes
Hi @Little-Night-Wolf thank you for you contribution. Hi, I would prefer to keep system variables, like $fn, outside of the module.

Changing that and adding the documentation of what you've added to the README would be ready for approval.

2023-07-27 09:00 UTC, Little-Night-Wolf commented
Hello @RaulBejarano I have already put the system variables outside of the model variables and I have modified the readme if you need any other change please let me know and I will make the change as soon as possible

I por cierto he visto tu cuenta y pone que eres de Bilbao a sí que supongo que hablas español, yo también, soy de Barcelona, no sé por qué hemos estado hablando en inglés

2023-07-27 10:45 UTC, RaulBejarano approved these changes

2023-07-27 10:46 UTC, RaulBejarano commented
Thank you so much. It's a pleasure to have you as a contributor.

PS: Si, soy de Bilbao. Lo del inglés es porque como es open-source pues es conveniente utilizarlo y así puede colaborar más gente.

2023-07-27 10:47 UTC, merged